Because the current Bundler version (2.4.1) does not satisfy bundler ~> 2.3.5   and Gemfile depends on bundler ~> 2.3.5,   version solving has failed.
Your bundle requires a different version of Bundler than the one you're running.
Install the necessary version with `gem install bundler:2.3.26` and rerun
bundler using `bundle _2.3.26_ install`
Error: Process completed with exit code 6.